version: '3' 

services:
  db:
    image: postgres:14  
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data-volume:/var/lib/postgresql/data

  web-init:
    build: ./web-app
    command: /code/initserver.sh
    volumes:
      - ./web-app:/code
    depends_on:
      - db
    links:
      - db

  web:
    build: ./web-app
    # user: nobody 
    command: /code/runserver.sh
    volumes:
      - ./web-app:/code
    expose:
      - "8000"
    depends_on:
      - db
      - web-init
    links:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  data-volume:
